// Code generated by counterfeiter. DO NOT EDIT.
package migratorfakes

import (
	"log"
	"sync"

	"code.cloudfoundry.org/cc-to-perm-migrator/migrator"
	"code.cloudfoundry.org/cc-to-perm-migrator/migrator/retriever"
	"code.cloudfoundry.org/lager"
)

type FakeRetriever struct {
	FetchCAPIEntitiesStub        func(logger lager.Logger, progress *log.Logger, assignments chan<- retriever.RoleAssignment, errs chan<- error)
	fetchCAPIEntitiesMutex       sync.RWMutex
	fetchCAPIEntitiesArgsForCall []struct {
		logger      lager.Logger
		progress    *log.Logger
		assignments chan<- retriever.RoleAssignment
		errs        chan<- error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRetriever) FetchCAPIEntities(logger lager.Logger, progress *log.Logger, assignments chan<- retriever.RoleAssignment, errs chan<- error) {
	fake.fetchCAPIEntitiesMutex.Lock()
	fake.fetchCAPIEntitiesArgsForCall = append(fake.fetchCAPIEntitiesArgsForCall, struct {
		logger      lager.Logger
		progress    *log.Logger
		assignments chan<- retriever.RoleAssignment
		errs        chan<- error
	}{logger, progress, assignments, errs})
	fake.recordInvocation("FetchCAPIEntities", []interface{}{logger, progress, assignments, errs})
	fake.fetchCAPIEntitiesMutex.Unlock()
	if fake.FetchCAPIEntitiesStub != nil {
		fake.FetchCAPIEntitiesStub(logger, progress, assignments, errs)
	}
}

func (fake *FakeRetriever) FetchCAPIEntitiesCallCount() int {
	fake.fetchCAPIEntitiesMutex.RLock()
	defer fake.fetchCAPIEntitiesMutex.RUnlock()
	return len(fake.fetchCAPIEntitiesArgsForCall)
}

func (fake *FakeRetriever) FetchCAPIEntitiesArgsForCall(i int) (lager.Logger, *log.Logger, chan<- retriever.RoleAssignment, chan<- error) {
	fake.fetchCAPIEntitiesMutex.RLock()
	defer fake.fetchCAPIEntitiesMutex.RUnlock()
	return fake.fetchCAPIEntitiesArgsForCall[i].logger, fake.fetchCAPIEntitiesArgsForCall[i].progress, fake.fetchCAPIEntitiesArgsForCall[i].assignments, fake.fetchCAPIEntitiesArgsForCall[i].errs
}

func (fake *FakeRetriever) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchCAPIEntitiesMutex.RLock()
	defer fake.fetchCAPIEntitiesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRetriever) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migrator.Retriever = new(FakeRetriever)
