// Code generated by counterfeiter. DO NOT EDIT.
package migratorfakes

import (
	"io"
	"sync"

	"code.cloudfoundry.org/cc-to-perm-migrator/migrator"
	"code.cloudfoundry.org/cc-to-perm-migrator/migrator/models"
)

type FakeReporter struct {
	GenerateReportStub        func(w io.Writer, orgs []models.Organization, spaces []models.Space, errs []error)
	generateReportMutex       sync.RWMutex
	generateReportArgsForCall []struct {
		w      io.Writer
		orgs   []models.Organization
		spaces []models.Space
		errs   []error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReporter) GenerateReport(w io.Writer, orgs []models.Organization, spaces []models.Space, errs []error) {
	var orgsCopy []models.Organization
	if orgs != nil {
		orgsCopy = make([]models.Organization, len(orgs))
		copy(orgsCopy, orgs)
	}
	var spacesCopy []models.Space
	if spaces != nil {
		spacesCopy = make([]models.Space, len(spaces))
		copy(spacesCopy, spaces)
	}
	var errsCopy []error
	if errs != nil {
		errsCopy = make([]error, len(errs))
		copy(errsCopy, errs)
	}
	fake.generateReportMutex.Lock()
	fake.generateReportArgsForCall = append(fake.generateReportArgsForCall, struct {
		w      io.Writer
		orgs   []models.Organization
		spaces []models.Space
		errs   []error
	}{w, orgsCopy, spacesCopy, errsCopy})
	fake.recordInvocation("GenerateReport", []interface{}{w, orgsCopy, spacesCopy, errsCopy})
	fake.generateReportMutex.Unlock()
	if fake.GenerateReportStub != nil {
		fake.GenerateReportStub(w, orgs, spaces, errs)
	}
}

func (fake *FakeReporter) GenerateReportCallCount() int {
	fake.generateReportMutex.RLock()
	defer fake.generateReportMutex.RUnlock()
	return len(fake.generateReportArgsForCall)
}

func (fake *FakeReporter) GenerateReportArgsForCall(i int) (io.Writer, []models.Organization, []models.Space, []error) {
	fake.generateReportMutex.RLock()
	defer fake.generateReportMutex.RUnlock()
	return fake.generateReportArgsForCall[i].w, fake.generateReportArgsForCall[i].orgs, fake.generateReportArgsForCall[i].spaces, fake.generateReportArgsForCall[i].errs
}

func (fake *FakeReporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.generateReportMutex.RLock()
	defer fake.generateReportMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migrator.Reporter = new(FakeReporter)
