#!/bin/bash

set -eu

JOB_NAME=cc-to-perm-migrator
LOG_DIR=/var/vcap/sys/log/${JOB_NAME}

mkdir -p "$LOG_DIR"
chown -R vcap:vcap "$LOG_DIR"

exec 2> >(tee -a "${LOG_DIR}/${JOB_NAME}.stderr.log")
exec > >(tee -a "${LOG_DIR}/${JOB_NAME}.stdout.log")

/var/vcap/packages/cc-to-perm-migrator/bin/cc-to-perm-migrator \
  --config-file-path=/var/vcap/jobs/${JOB_NAME}/config/cc-to-perm-migrator.yml
