// Code generated by counterfeiter. DO NOT EDIT.
package cmdfakes

import (
	"io"
	"sync"

	"code.cloudfoundry.org/cc-to-perm-migrator/cloudcontroller"
	"code.cloudfoundry.org/cc-to-perm-migrator/cmd"
	"code.cloudfoundry.org/lager"
)

type FakeCloudControllerAPIClient struct {
	MakePaginatedGetRequestStub        func(logger lager.Logger, route string, bodyCallback func(lager.Logger, io.Reader) error) error
	makePaginatedGetRequestMutex       sync.RWMutex
	makePaginatedGetRequestArgsForCall []struct {
		logger       lager.Logger
		route        string
		bodyCallback func(lager.Logger, io.Reader) error
	}
	makePaginatedGetRequestReturns struct {
		result1 error
	}
	makePaginatedGetRequestReturnsOnCall map[int]struct {
		result1 error
	}
	GetOrganizationsStub        func(logger lager.Logger) ([]cloudcontroller.OrganizationResource, error)
	getOrganizationsMutex       sync.RWMutex
	getOrganizationsArgsForCall []struct {
		logger lager.Logger
	}
	getOrganizationsReturns struct {
		result1 []cloudcontroller.OrganizationResource
		result2 error
	}
	getOrganizationsReturnsOnCall map[int]struct {
		result1 []cloudcontroller.OrganizationResource
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCloudControllerAPIClient) MakePaginatedGetRequest(logger lager.Logger, route string, bodyCallback func(lager.Logger, io.Reader) error) error {
	fake.makePaginatedGetRequestMutex.Lock()
	ret, specificReturn := fake.makePaginatedGetRequestReturnsOnCall[len(fake.makePaginatedGetRequestArgsForCall)]
	fake.makePaginatedGetRequestArgsForCall = append(fake.makePaginatedGetRequestArgsForCall, struct {
		logger       lager.Logger
		route        string
		bodyCallback func(lager.Logger, io.Reader) error
	}{logger, route, bodyCallback})
	fake.recordInvocation("MakePaginatedGetRequest", []interface{}{logger, route, bodyCallback})
	fake.makePaginatedGetRequestMutex.Unlock()
	if fake.MakePaginatedGetRequestStub != nil {
		return fake.MakePaginatedGetRequestStub(logger, route, bodyCallback)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.makePaginatedGetRequestReturns.result1
}

func (fake *FakeCloudControllerAPIClient) MakePaginatedGetRequestCallCount() int {
	fake.makePaginatedGetRequestMutex.RLock()
	defer fake.makePaginatedGetRequestMutex.RUnlock()
	return len(fake.makePaginatedGetRequestArgsForCall)
}

func (fake *FakeCloudControllerAPIClient) MakePaginatedGetRequestArgsForCall(i int) (lager.Logger, string, func(lager.Logger, io.Reader) error) {
	fake.makePaginatedGetRequestMutex.RLock()
	defer fake.makePaginatedGetRequestMutex.RUnlock()
	return fake.makePaginatedGetRequestArgsForCall[i].logger, fake.makePaginatedGetRequestArgsForCall[i].route, fake.makePaginatedGetRequestArgsForCall[i].bodyCallback
}

func (fake *FakeCloudControllerAPIClient) MakePaginatedGetRequestReturns(result1 error) {
	fake.MakePaginatedGetRequestStub = nil
	fake.makePaginatedGetRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudControllerAPIClient) MakePaginatedGetRequestReturnsOnCall(i int, result1 error) {
	fake.MakePaginatedGetRequestStub = nil
	if fake.makePaginatedGetRequestReturnsOnCall == nil {
		fake.makePaginatedGetRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.makePaginatedGetRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudControllerAPIClient) GetOrganizations(logger lager.Logger) ([]cloudcontroller.OrganizationResource, error) {
	fake.getOrganizationsMutex.Lock()
	ret, specificReturn := fake.getOrganizationsReturnsOnCall[len(fake.getOrganizationsArgsForCall)]
	fake.getOrganizationsArgsForCall = append(fake.getOrganizationsArgsForCall, struct {
		logger lager.Logger
	}{logger})
	fake.recordInvocation("GetOrganizations", []interface{}{logger})
	fake.getOrganizationsMutex.Unlock()
	if fake.GetOrganizationsStub != nil {
		return fake.GetOrganizationsStub(logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getOrganizationsReturns.result1, fake.getOrganizationsReturns.result2
}

func (fake *FakeCloudControllerAPIClient) GetOrganizationsCallCount() int {
	fake.getOrganizationsMutex.RLock()
	defer fake.getOrganizationsMutex.RUnlock()
	return len(fake.getOrganizationsArgsForCall)
}

func (fake *FakeCloudControllerAPIClient) GetOrganizationsArgsForCall(i int) lager.Logger {
	fake.getOrganizationsMutex.RLock()
	defer fake.getOrganizationsMutex.RUnlock()
	return fake.getOrganizationsArgsForCall[i].logger
}

func (fake *FakeCloudControllerAPIClient) GetOrganizationsReturns(result1 []cloudcontroller.OrganizationResource, result2 error) {
	fake.GetOrganizationsStub = nil
	fake.getOrganizationsReturns = struct {
		result1 []cloudcontroller.OrganizationResource
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudControllerAPIClient) GetOrganizationsReturnsOnCall(i int, result1 []cloudcontroller.OrganizationResource, result2 error) {
	fake.GetOrganizationsStub = nil
	if fake.getOrganizationsReturnsOnCall == nil {
		fake.getOrganizationsReturnsOnCall = make(map[int]struct {
			result1 []cloudcontroller.OrganizationResource
			result2 error
		})
	}
	fake.getOrganizationsReturnsOnCall[i] = struct {
		result1 []cloudcontroller.OrganizationResource
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudControllerAPIClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.makePaginatedGetRequestMutex.RLock()
	defer fake.makePaginatedGetRequestMutex.RUnlock()
	fake.getOrganizationsMutex.RLock()
	defer fake.getOrganizationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCloudControllerAPIClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmd.CloudControllerAPIClient = new(FakeCloudControllerAPIClient)
