#!/bin/bash

set -eu

LOG_DIR=/var/vcap/sys/log/cloud-controller-migrator

mkdir -p "$LOG_DIR"
chown -R vcap:vcap "$LOG_DIR"

exec > >(tee -a "${LOG_DIR}/cloud-controller-migrator.stdout.log")
exec 2> >(tee -a "${LOG_DIR}/cloud-controller-migrator.stderr.log")

/var/vcap/packages/cloud-controller-migrator/bin/cloud-controller-migrator \
  --config-file-path=/var/vcap/jobs/cloud-controller-migrator/config/cloud-controller-migrator.yml
